name: todo_app
version: 0.2.0
dependencies:
  angular2: 2.0.0-beta.7
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
  uuid: ^0.5.0
dev_dependencies:
  angular2_testing: "^2.0.0-beta.7"
  test: '^0.12.6'
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
